name: 'Setup .NET Environment'
description: 'Set up .NET SDK, configure dependency caching, restore, and optionally build'
inputs:
  build:
    description: 'Whether to run dotnet build after restore'
    required: false
    default: 'true'
runs:
  using: 'composite'
  steps:
    - name: Set up .NET
      uses: actions/setup-dotnet@v5
      with:
        global-json-file: global.json

    - name: Set up dependency caching for faster builds
      uses: actions/cache@v5
      with:
        path: |
          ~/.nuget/packages
          ${{ github.workspace }}/**/obj/project.assets.json
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          ${{ runner.os }}-nuget-

    - name: Restore .NET dependencies
      shell: bash
      run: dotnet restore

    - name: Build with dotnet
      if: inputs.build == 'true'
      shell: bash
      run: dotnet build -p:ContinuousIntegrationBuild=True -p:ReleaseDateAttribute=True --configuration Release --no-restore
